Invoke-Expression -Command "winget install neovim"
Invoke-Expression -Command "winget install QL-Win.QuickLook"
Invoke-Expression -Command "winget install stedolan.jq"
Invoke-Expression -Command "winget install gsudo"
Invoke-Expression -Command "winget install GnuWin32.grep"
Invoke-Expression -Command "winget install LGUG2Z.komorebi"
Invoke-Expression -Command "winget install --id Microsoft.Powershell --source winget"
Invoke-Expression -Command "winget install JanDeDobbeleer.OhMyPosh"
Invoke-Expression -Command "winget install Github.cli"
Invoke-Expression -Command "winget install Yarn.Yarn"
Invoke-Expression -Command "winget install OpenJS.NodeJS"
Invoke-Expression -Command "yarn global add tree-sitter-cli"
Invoke-Expression -Command "cargo install fd-find"
Install-Module -Name Terminal-Icons -Repository PSGallery
Invoke-Expression -Command "irm get.scoop.sh | iex"
Invoke-Expression -Command "scoop bucket add extras"
Invoke-Expression -Command "scoop install autohotkey2"
Invoke-Expression -Command "winget install GnuWin32.Make"
Invoke-Expression -Command "winget install OlegShparber.Zeal"
Invoke-Expression -Command "winget install SpeedCrunch.SpeedCrunch"
Invoke-Expression -Command "winget install ShareX.ShareX"
Invoke-Expression -Command "winget install twinkletray"
