; Sort of Generated by komorebic

; 1Password
Run komorebic float-rule exe 1Password.exe, , "Hide"

; Adobe Creative Cloud
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application class CreativeCloudDesktopWindowClass, , "Hide"

; AutoHotkey
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe AutoHotkeyU64.exe, , "Hide"
Run komorebic float-rule title Window Spy, , "Hide"

Run komorebic float-rule exe Battle.net.exe, , "Hide"

; Bitwarden
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Bitwarden.exe, , "Hide"

; Calculator
Run komorebic float-rule title Calculator, , "Hide"

; Credential Manager UI Host
; Targets the Windows popup prompting you for a PIN instead of a password on 1Password etc.
Run komorebic float-rule exe CredentialUIBroker.exe, , "Hide"

; Cron
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Cron.exe, , "Hide"

; Discord
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Discord.exe, , "Hide"
Run komorebic identify-border-overflow-application exe Discord.exe, , "Hide"

; DiscordCanary
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe DiscordCanary.exe, , "Hide"

; DiscordDevelopment
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe DiscordDeveloper.exe, , "Hide"

; DiscordPTB
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe DiscordPTB.exe, , "Hide"

; ElectronMail
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ElectronMail.exe, , "Hide"

; Element
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Element.exe, , "Hide"

; ElevenClock
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ElevenClock.exe, , "Hide"

; Epic Games Launcher
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic float-rule exe EpicGamesLauncher.exe, , "Hide"
Run komorebic identify-tray-application exe EpicGamesLauncher.exe, , "Hide"

; Flow Launcher
Run komorebic identify-border-overflow-application exe Flow.Launcher.exe, , "Hide"

; Google Drive
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe GoogleDriveFS.exe, , "Hide"

; Inno Setup
; Target hidden window spawned by Inno Setup applications
Run komorebic float-rule class TApplication, , "Hide"
; Target Inno Setup installers
Run komorebic float-rule class TWizardForm, , "Hide"

; IntelliJ IDEA
Run komorebic identify-object-name-change-application exe idea64.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe idea64.exe, , "Hide"
; Targets JetBrains IDE popups and floating windows
Run komorebic float-rule class SunAwtDialog, , "Hide"

; Kleopatra
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe kleopatra.exe, , "Hide"


; Logi Bolt
Run komorebic float-rule exe LogiBolt.exe, , "Hide"

; LogiTune
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe LogiTune.exe, , "Hide"
Run komorebic float-rule exe LogiTune.exe, , "Hide"

; Logitech G HUB
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe lghub.exe, , "Hide"
Run komorebic identify-border-overflow-application exe lghub.exe, , "Hide"

; Logitech Options
Run komorebic float-rule exe LogiOptionsUI.exe, , "Hide"


; Microsoft Excel
Run komorebic identify-border-overflow-application exe EXCEL.EXE, , "Hide"
Run komorebic identify-layered-application exe EXCEL.EXE, , "Hide"
; Targets a hidden window spawned by Microsoft Office applications
Run komorebic float-rule class _WwB, , "Hide"

; Microsoft Outlook
Run komorebic identify-border-overflow-application exe OUTLOOK.EXE, , "Hide"
Run komorebic identify-layered-application exe OUTLOOK.EXE, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe OUTLOOK.EXE, , "Hide"

; Microsoft PowerPoint
Run komorebic identify-border-overflow-application exe POWERPNT.EXE, , "Hide"
Run komorebic identify-layered-application exe POWERPNT.EXE, , "Hide"

; Microsoft Teams
; Target Teams pop-up notification windows
Run komorebic float-rule title Microsoft Teams Notifications, , "Hide"

; Microsoft Word
Run komorebic identify-border-overflow-application exe WINWORD.EXE, , "Hide"
Run komorebic identify-layered-application exe WINWORD.EXE, , "Hide"

; Modern Flyouts
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ModernFlyoutsHost.exe, , "Hide"

; Mozilla Firefox
Run komorebic identify-object-name-change-application exe firefox.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe firefox.exe, , "Hide"
; Targets invisible windows spawned by Firefox to show tab previews in the taskbar
Run komorebic float-rule class MozillaTaskbarPreviewClass, , "Hide"

; NVIDIA GeForce Experience
Run komorebic identify-border-overflow-application exe NVIDIA GeForce Experience.exe, , "Hide"

; OBS Studio (32-bit)
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe obs32.exe, , "Hide"

; OBS Studio (64-bit)
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe obs64.exe, , "Hide"

; OpenRGB
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe OpenRGB.exe, , "Hide"

; PowerToys
; Target color picker dialog
Run komorebic float-rule exe PowerToys.ColorPickerUI.exe, , "Hide"
; Target image resizer dialog
Run komorebic float-rule exe PowerToys.ImageResizer.exe, , "Hide"

; Process Hacker
Run komorebic identify-border-overflow-application exe ProcessHacker.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ProcessHacker.exe, , "Hide"
Run komorebic float-rule exe ProcessHacker.exe, , "Hide"

; ProtonVPN
Run komorebic identify-border-overflow-application exe ProtonVPN.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ProtonVPN.exe, , "Hide"

; PyCharm
Run komorebic identify-object-name-change-application exe pycharm64.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe pycharm64.exe, , "Hide"

; QuickLook
Run komorebic float-rule exe QuickLook.exe, , "Hide"

; RepoZ
Run komorebic float-rule exe RepoZ.exe, , "Hide"

; Roblox FPS Unlocker
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe rbxfpsunlocker.exe, , "Hide"

; RoundedTB
Run komorebic float-rule exe RoundedTB.exe, , "Hide"

; RoundedTB
Run komorebic identify-border-overflow-application exe RoundedTB.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe RoundedTB.exe, , "Hide"

; ShareX
Run komorebic identify-border-overflow-application exe ShareX.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ShareX.exe, , "Hide"

; Signal
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe signal.exe, , "Hide"
Run komorebic identify-border-overflow-application exe signal.exe, , "Hide"

; Signal
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe WhatsApp.exe, , "Hide"
Run komorebic identify-border-overflow-application exe WhatsApp.exe, , "Hide"

; SiriKali
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe sirikali.exe, , "Hide"

; Slack
Run komorebic identify-border-overflow-application exe Slack.exe, , "Hide"
;Run komorebic manage-rule exe Slack.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Slack.exe, , "Hide"

; Spotify
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Spotify.exe, , "Hide"

; Steam
Run komorebic identify-border-overflow-application class vguiPopupWindow, , "Hide"
Run komorebic float-rule exe 1Password.exe, , "Hide"

; Task Manager
Run komorebic float-rule class TaskManagerWindow, , "Hide"

; Telegram
Run komorebic identify-border-overflow-application exe Telegram.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe Telegram.exe, , "Hide"

; Unreal Editor
Run komorebic identify-border-overflow-application exe UnrealEditor.exe, , "Hide"
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe UnrealEditor.exe, , "Hide"
Run komorebic float-rule exe UnrealEditor.exe, , "Hide"

; Visual Studio Code
Run komorebic identify-border-overflow-application exe Code.exe, , "Hide"

; Windows Console (conhost.exe)
; Run komorebic manage-rule class ConsoleWindowClass, , "Hide"

; Windows Explorer
; Targets copy/move operation windows
Run komorebic float-rule class OperationStatusWindow, , "Hide"
Run komorebic float-rule title Control Panel, , "Hide"

; Windows Installer
; Targets MSI Installers
Run komorebic float-rule class MsiDialogCloseClass, , "Hide"

; Wox
; Targets a hidden window spawned by Wox
Run komorebic float-rule title Hotkey sink, , "Hide"

; Zoom
Run komorebic float-rule exe Zoom.exe, , "Hide"

; qBittorrent
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe qbittorrent.exe, , "Hide"

; ueli
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run komorebic identify-tray-application exe ueli.exe, , "Hide"
Run komorebic float-rule exe ueli.exe, , "Hide"

; GitHub Desktop
Run komorebic identify-tray-application exe GitHubDesktop.exe, , "Hide"
Run komorebic identify-border-overflow-application exe GitHubDesktop.exe, , "Hide"
